"use server";

import { revalidatePath } from "next/cache";

import { mutateConvex, queryConvex } from "@/lib/platform/convex/server";
import { guardCredentialTracking } from "@/lib/plans/guards";
import {
  teamCredentialSchema,
  teamDocumentSchema,
  teamMemberSchema,
  teamTaskSchema,
} from "@/lib/validations/team";

type ActionResult<T = void> =
  | { success: true; data?: T }
  | { success: false; error: string };

export interface TeamMember {
  id: string;
  profile_id: string;
  first_name: string;
  last_name: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  role: string | null;
  notes: string | null;
  status: "active" | "inactive";
  hired_date: string | null;
  job_application_id: string | null;
  created_at: string;
  updated_at: string;
  credential_count?: number;
  expiring_credential_count?: number;
}

export interface TeamCredential {
  id: string;
  team_member_id: string | null;
  profile_id: string;
  employee_name: string;
  credential_name: string;
  expiration_date: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface TeamDocument {
  id: string;
  team_member_id: string;
  label: string | null;
  url: string | null;
  file_path: string | null;
  notes: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface TeamTask {
  id: string;
  client_id: string | null;
  team_member_id: string | null;
  profile_id: string;
  title: string;
  content: string | null;
  status: "pending" | "in_progress" | "completed";
  due_date: string | null;
  auto_generated: boolean;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

type ConvexTeamMember = {
  id: string;
  workspaceId: string;
  firstName: string;
  lastName: string;
  email: string | null;
  phone: string | null;
  address: string | null;
  role: string | null;
  notes: string | null;
  status: "active" | "inactive";
  hireDate: string | null;
  createdAt: string;
  updatedAt: string;
  credentialCount?: number;
  expiringCredentialCount?: number;
};

type ConvexTeamCredential = {
  id: string;
  memberId: string;
  name: string;
  expirationDate: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

type ConvexTeamDocument = {
  id: string;
  memberId: string;
  name: string;
  fileUrl: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

type ConvexTeamTask = {
  id: string;
  teamMemberId: string;
  title: string;
  content: string | null;
  status: "pending" | "in_progress" | "completed";
  dueDate: string | null;
  autoGenerated: boolean;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

function mapTeamMember(member: ConvexTeamMember): TeamMember {
  return {
    id: member.id,
    profile_id: member.workspaceId,
    first_name: member.firstName,
    last_name: member.lastName || null,
    email: member.email,
    phone: member.phone,
    address: member.address,
    role: member.role,
    notes: member.notes,
    status: member.status,
    hired_date: member.hireDate,
    job_application_id: null,
    created_at: member.createdAt,
    updated_at: member.updatedAt,
    credential_count: member.credentialCount ?? 0,
    expiring_credential_count: member.expiringCredentialCount ?? 0,
  };
}

function mapTeamCredential(credential: ConvexTeamCredential, profileId: string, employeeName: string): TeamCredential {
  return {
    id: credential.id,
    team_member_id: credential.memberId,
    profile_id: profileId,
    employee_name: employeeName,
    credential_name: credential.name,
    expiration_date: credential.expirationDate,
    notes: credential.notes,
    created_at: credential.createdAt,
    updated_at: credential.updatedAt,
  };
}

function mapTeamDocument(document: ConvexTeamDocument): TeamDocument {
  return {
    id: document.id,
    team_member_id: document.memberId,
    label: document.name,
    url: document.fileUrl,
    file_path: null,
    notes: document.notes,
    sort_order: 0,
    created_at: document.createdAt,
    updated_at: document.updatedAt,
  };
}

function mapTeamTask(task: ConvexTeamTask, profileId: string): TeamTask {
  return {
    id: task.id,
    client_id: null,
    team_member_id: task.teamMemberId,
    profile_id: profileId,
    title: task.title,
    content: task.content,
    status: task.status,
    due_date: task.dueDate,
    auto_generated: task.autoGenerated,
    completed_at: task.completedAt,
    created_at: task.createdAt,
    updated_at: task.updatedAt,
  };
}

async function ensureTeamAccess() {
  const guard = await guardCredentialTracking();
  if (!guard.allowed) {
    return { success: false as const, error: guard.reason };
  }

  return null;
}

async function getTeamMemberPayload(memberId: string) {
  const result = await queryConvex<{
    member: ConvexTeamMember;
    credentials: ConvexTeamCredential[];
    documents: ConvexTeamDocument[];
    tasks: ConvexTeamTask[];
  } | null>("team:getTeamMember", { memberId });

  if (!result) {
    return null;
  }

  const member = mapTeamMember(result.member);
  const employeeName = [member.first_name, member.last_name].filter(Boolean).join(" ");

  return {
    member,
    credentials: result.credentials.map((credential) =>
      mapTeamCredential(credential, member.profile_id, employeeName),
    ),
    documents: result.documents.map(mapTeamDocument),
    tasks: result.tasks.map((task) => mapTeamTask(task, member.profile_id)),
  };
}

export async function getTeamMembers(): Promise<ActionResult<TeamMember[]>> {
  const access = await ensureTeamAccess();
  if (access) {
    return access;
  }

  try {
    const result = await queryConvex<ConvexTeamMember[]>("team:getTeamMembers");
    return { success: true, data: result.map(mapTeamMember) };
  } catch (error) {
    console.error("[TEAM] Convex getTeamMembers error:", error);
    return { success: false, error: "Failed to load team members" };
  }
}

export async function getTeamMember(
  memberId: string,
): Promise<
  ActionResult<{
    member: TeamMember;
    credentials: TeamCredential[];
    documents: TeamDocument[];
    tasks: TeamTask[];
  }>
> {
  try {
    const result = await getTeamMemberPayload(memberId);
    if (!result) {
      return { success: false, error: "Team member not found" };
    }

    return { success: true, data: result };
  } catch (error) {
    console.error("[TEAM] Convex getTeamMember error:", error);
    return { success: false, error: "Team member not found" };
  }
}

export async function createTeamMember(
  data: Record<string, unknown>,
): Promise<ActionResult<{ id: string }>> {
  const access = await ensureTeamAccess();
  if (access) {
    return access;
  }

  const parsed = teamMemberSchema.safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    const result = await mutateConvex<{ id: string }>("team:createTeamMember", {
      firstName: parsed.data.first_name,
      lastName: parsed.data.last_name || undefined,
      email: parsed.data.email || undefined,
      phone: parsed.data.phone || undefined,
      address: parsed.data.address || undefined,
      role: parsed.data.role || undefined,
      notes: parsed.data.notes || undefined,
      hireDate: parsed.data.hired_date || undefined,
    });
    revalidatePath("/dashboard/team/employees");
    return { success: true, data: result };
  } catch (error) {
    console.error("[TEAM] Convex createTeamMember error:", error);
    return { success: false, error: "Failed to create team member" };
  }
}

export async function updateTeamMember(
  memberId: string,
  data: Record<string, unknown>,
): Promise<ActionResult> {
  const parsed = teamMemberSchema.partial().safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    await mutateConvex("team:updateTeamMember", {
      memberId,
      firstName: parsed.data.first_name ?? undefined,
      lastName: parsed.data.last_name ?? undefined,
      email: parsed.data.email ?? undefined,
      phone: parsed.data.phone ?? undefined,
      address: parsed.data.address ?? undefined,
      role: parsed.data.role ?? undefined,
      notes: parsed.data.notes ?? undefined,
      status: parsed.data.status ?? undefined,
      hireDate: parsed.data.hired_date ?? undefined,
    });
    revalidatePath("/dashboard/team/employees");
    revalidatePath(`/dashboard/team/employees/${memberId}`);
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex updateTeamMember error:", error);
    return { success: false, error: "Failed to update team member" };
  }
}

export async function deleteTeamMember(memberId: string): Promise<ActionResult> {
  try {
    await mutateConvex("team:deleteTeamMember", { memberId });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex deleteTeamMember error:", error);
    return { success: false, error: "Failed to delete team member" };
  }
}

export async function addTeamCredential(
  teamMemberId: string,
  data: Record<string, unknown>,
): Promise<ActionResult<{ id: string }>> {
  const parsed = teamCredentialSchema.safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    const result = await mutateConvex<{ id: string }>("team:addTeamCredential", {
      memberId: teamMemberId,
      type: "credential",
      name: parsed.data.credential_name,
      expirationDate: parsed.data.expiration_date || undefined,
      notes: parsed.data.notes || undefined,
    });
    revalidatePath(`/dashboard/team/employees/${teamMemberId}`);
    return { success: true, data: result };
  } catch (error) {
    console.error("[TEAM] Convex addTeamCredential error:", error);
    return { success: false, error: "Failed to add credential" };
  }
}

export async function updateTeamCredential(
  credentialId: string,
  data: Record<string, unknown>,
): Promise<ActionResult> {
  const parsed = teamCredentialSchema.partial().safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    await mutateConvex("team:updateTeamCredential", {
      credentialId,
      name: parsed.data.credential_name ?? undefined,
      expirationDate: parsed.data.expiration_date ?? undefined,
      notes: parsed.data.notes ?? undefined,
    });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex updateTeamCredential error:", error);
    return { success: false, error: "Failed to update credential" };
  }
}

export async function deleteTeamCredential(credentialId: string): Promise<ActionResult> {
  try {
    await mutateConvex("team:deleteTeamCredential", { credentialId });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex deleteTeamCredential error:", error);
    return { success: false, error: "Failed to delete credential" };
  }
}

export async function addTeamDocument(
  teamMemberId: string,
  data: Record<string, unknown>,
): Promise<ActionResult<{ id: string }>> {
  const parsed = teamDocumentSchema.safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    const result = await mutateConvex<{ id: string }>("team:addTeamDocument", {
      memberId: teamMemberId,
      name: parsed.data.label,
      fileUrl: parsed.data.url || undefined,
      notes: parsed.data.notes || undefined,
    });
    revalidatePath(`/dashboard/team/employees/${teamMemberId}`);
    return { success: true, data: result };
  } catch (error) {
    console.error("[TEAM] Convex addTeamDocument error:", error);
    return { success: false, error: "Failed to add document" };
  }
}

export async function deleteTeamDocument(documentId: string): Promise<ActionResult> {
  try {
    await mutateConvex("team:deleteTeamDocument", { documentId });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex deleteTeamDocument error:", error);
    return { success: false, error: "Failed to delete document" };
  }
}

export async function getTeamMemberTasks(teamMemberId: string): Promise<ActionResult<TeamTask[]>> {
  try {
    const memberPayload = await getTeamMemberPayload(teamMemberId);
    if (memberPayload) {
      return { success: true, data: memberPayload.tasks };
    }

    const tasks = await queryConvex<ConvexTeamTask[]>("team:getTeamMemberTasks", { teamMemberId });
    return { success: true, data: tasks.map((task) => mapTeamTask(task, "")) };
  } catch (error) {
    console.error("[TEAM] Convex getTeamMemberTasks error:", error);
    return { success: false, error: "Failed to load tasks" };
  }
}

export async function createTeamTask(
  teamMemberId: string,
  data: Record<string, unknown>,
): Promise<ActionResult<{ id: string }>> {
  const parsed = teamTaskSchema.safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    const result = await mutateConvex<{ id: string }>("team:createTeamTask", {
      teamMemberId,
      title: parsed.data.title,
      content: parsed.data.content || null,
      status: parsed.data.status || "pending",
      dueDate: parsed.data.due_date || null,
    });
    revalidatePath(`/dashboard/team/employees/${teamMemberId}`);
    return { success: true, data: result };
  } catch (error) {
    console.error("[TEAM] Convex createTeamTask error:", error);
    return { success: false, error: "Failed to create task" };
  }
}

export async function updateTeamTask(
  taskId: string,
  data: Record<string, unknown>,
): Promise<ActionResult> {
  const parsed = teamTaskSchema.partial().safeParse(data);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message || "Invalid input" };
  }

  try {
    await mutateConvex("team:updateTeamTask", {
      taskId,
      title: parsed.data.title ?? undefined,
      content: parsed.data.content ?? undefined,
      status: parsed.data.status ?? undefined,
      dueDate: parsed.data.due_date ?? undefined,
    });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex updateTeamTask error:", error);
    return { success: false, error: "Failed to update task" };
  }
}

export async function completeTeamTask(taskId: string): Promise<ActionResult> {
  try {
    await mutateConvex("team:completeTeamTask", { taskId });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex completeTeamTask error:", error);
    return { success: false, error: "Failed to complete task" };
  }
}

export async function deleteTeamTask(taskId: string): Promise<ActionResult> {
  try {
    await mutateConvex("team:deleteTeamTask", { taskId });
    revalidatePath("/dashboard/team/employees");
    return { success: true };
  } catch (error) {
    console.error("[TEAM] Convex deleteTeamTask error:", error);
    return { success: false, error: "Failed to delete task" };
  }
}
