import type { ClientDetail } from "@/lib/actions/clients";

import { DEMO_CLIENTS } from "./data";

const DEMO_PROFILE_ID = "demo-profile";

function getDateOnly(value: string) {
  return value.split("T")[0] ?? value;
}

function getListClient(id: string) {
  const client = DEMO_CLIENTS.find((item) => item.id === id);
  if (!client) {
    throw new Error(`Unknown demo client: ${id}`);
  }

  return client;
}

function createDemoClientDetail(
  id: string,
  overrides: Partial<ClientDetail>
): ClientDetail {
  const listClient = getListClient(id);

  return {
    id,
    profile_id: DEMO_PROFILE_ID,
    listing_id: "",
    inquiry_id: "",
    status: listClient.status,
    referral_source: "pediatrician",
    referral_source_other: "",
    referral_date: getDateOnly(listClient.created_at),
    service_start_date: "",
    service_end_date: "",
    discharge_reason: "",
    funding_source: "insurance",
    preferred_language: "English",
    child_first_name: listClient.child_first_name ?? undefined,
    child_last_name: listClient.child_last_name ?? undefined,
    child_date_of_birth: listClient.child_date_of_birth ?? undefined,
    child_diagnosis: [],
    child_diagnosis_codes: [],
    child_diagnosis_date: "",
    child_primary_concerns: "",
    child_aba_history: "",
    child_school_name: "",
    child_school_district: "",
    child_grade_level: "",
    child_other_therapies: "",
    child_pediatrician_name: "",
    child_pediatrician_phone: "",
    notes: "",
    created_at: listClient.created_at,
    updated_at: listClient.updated_at,
    parents: [],
    locations: [],
    insurances: [],
    authorizations: [],
    documents: [],
    tasks: [],
    contacts: [],
    ...overrides,
  };
}

export const DEMO_CLIENT_DETAILS: ClientDetail[] = [
  createDemoClientDetail("demo-client-1", {
    referral_source: "pediatrician",
    preferred_language: "Vietnamese",
    child_diagnosis: ["Autism Spectrum Disorder"],
    child_primary_concerns: "Parent is looking for in-home early intervention support focused on communication and transitions.",
    child_aba_history: "Recently completed an intake call. Family has not started ABA services before.",
    child_school_name: "Bright Start Preschool",
    child_grade_level: "preschool",
    child_pediatrician_name: "Dr. Mei Chen",
    child_pediatrician_phone: "(555) 210-8877",
    notes: "Family prefers weekday mornings and wants guidance on next steps for insurance verification.",
    parents: [
      {
        id: "demo-client-1-parent-1",
        created_at: "2026-03-22T10:00:00.000Z",
        first_name: "Trang",
        last_name: "Nguyen",
        relationship: "mother",
        phone: "(555) 201-3344",
        email: "trang.nguyen@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
      {
        id: "demo-client-1-parent-2",
        created_at: "2026-03-22T10:00:00.000Z",
        first_name: "Minh",
        last_name: "Nguyen",
        relationship: "father",
        phone: "(555) 201-7721",
        email: "minh.nguyen@example.com",
        notes: "",
        is_primary: false,
        sort_order: 1,
      },
    ],
    locations: [
      {
        id: "demo-client-1-location-1",
        created_at: "2026-03-22T10:00:00.000Z",
        label: "Home",
        street_address: "1420 Willow Grove Dr",
        city: "Austin",
        state: "TX",
        postal_code: "78748",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Family requested weekday morning availability.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-1-insurance-1",
        created_at: "2026-03-22T10:00:00.000Z",
        insurance_name: "Blue Cross Blue Shield",
        insurance_type: "commercial",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "BCBS-884712",
        group_number: "GRP-1102",
        plan_name: "PPO Family Plan",
        subscriber_relationship: "child",
        status: "pending_verification",
        copay_amount: 35,
        coinsurance_percentage: 20,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "demo-client-1-task-1",
        created_at: "2026-03-23T14:00:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Verify BCBS benefits",
        content: "",
        status: "pending",
        due_date: "2026-03-28",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-2", {
    referral_source: "agency_website",
    child_diagnosis: ["Autism Spectrum Disorder", "Speech Delay"],
    child_primary_concerns: "Family needs support with tantrums, communication, and potty-training readiness.",
    child_school_name: "Little Oaks Preschool",
    child_grade_level: "preschool",
    child_pediatrician_name: "Dr. Rohan Mehta",
    child_pediatrician_phone: "(555) 302-0041",
    notes: "Parent asked for bilingual therapist if available.",
    parents: [
      {
        id: "demo-client-2-parent-1",
        created_at: "2026-03-20T16:30:00.000Z",
        first_name: "Priya",
        last_name: "Patel",
        relationship: "mother",
        phone: "(555) 302-5567",
        email: "priya.patel@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-2-location-1",
        created_at: "2026-03-20T16:30:00.000Z",
        label: "Home",
        street_address: "981 Meadow Lake Ct",
        city: "Plano",
        state: "TX",
        postal_code: "75024",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Interested in center-based after school later this year.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-2-insurance-1",
        created_at: "2026-03-20T16:30:00.000Z",
        insurance_name: "Aetna",
        insurance_type: "commercial",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "AET-221098",
        group_number: "GRP-2408",
        plan_name: "Open Choice PPO",
        subscriber_relationship: "child",
        status: "pending_verification",
        copay_amount: 25,
        coinsurance_percentage: 10,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "demo-client-2-task-1",
        created_at: "2026-03-21T12:00:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Send intake packet",
        content: "",
        status: "in_progress",
        due_date: "2026-03-27",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-3", {
    referral_source: "school",
    child_diagnosis: ["Autism Spectrum Disorder"],
    child_primary_concerns: "Working through assessment scheduling and school coordination.",
    child_aba_history: "Received parent consultation through another provider last year.",
    child_school_name: "Riverbend Elementary",
    child_school_district: "Northside ISD",
    child_grade_level: "1st",
    child_pediatrician_name: "Dr. Elena Torres",
    child_pediatrician_phone: "(555) 403-1114",
    notes: "Family can only attend assessments after 3 PM.",
    parents: [
      {
        id: "demo-client-3-parent-1",
        created_at: "2026-03-04T09:00:00.000Z",
        first_name: "Maria",
        last_name: "Rivera",
        relationship: "mother",
        phone: "(555) 403-7789",
        email: "maria.r@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-3-location-1",
        created_at: "2026-03-04T09:00:00.000Z",
        label: "School",
        street_address: "6201 Riverbend Ave",
        city: "San Antonio",
        state: "TX",
        postal_code: "78250",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Assessment team coordinating classroom observation.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-3-insurance-1",
        created_at: "2026-03-04T09:00:00.000Z",
        insurance_name: "UnitedHealthcare",
        insurance_type: "commercial",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "UHC-556234",
        group_number: "GRP-8840",
        plan_name: "Choice Plus",
        subscriber_relationship: "child",
        status: "active",
        copay_amount: 40,
        coinsurance_percentage: 20,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    documents: [
      {
        id: "demo-client-3-document-1",
        created_at: "2026-03-18T11:00:00.000Z",
        document_type: "assessment",
        label: "Assessment intake form",
        url: "https://preview.findabatherapy.com/demo-client-3/assessment-intake",
        file_path: "",
        file_name: "assessment-intake.pdf",
        file_description: "",
        file_size: 182400,
        file_type: "application/pdf",
        upload_source: "dashboard",
        uploaded_by: undefined,
        notes: "Shared by the family before the first assessment block.",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "demo-client-3-task-1",
        created_at: "2026-03-19T09:30:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Confirm assessor availability",
        content: "",
        status: "pending",
        due_date: "2026-03-29",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-4", {
    referral_source: "insurance_referral",
    child_diagnosis: ["Autism Spectrum Disorder"],
    child_primary_concerns: "Awaiting final authorization after benefits were confirmed.",
    child_school_name: "Maple Grove Preschool",
    child_grade_level: "preschool",
    child_pediatrician_name: "Dr. Hannah Park",
    child_pediatrician_phone: "(555) 504-9022",
    notes: "Parent wants center-based services two afternoons per week.",
    parents: [
      {
        id: "demo-client-4-parent-1",
        created_at: "2026-02-24T13:00:00.000Z",
        first_name: "Jisoo",
        last_name: "Kim",
        relationship: "mother",
        phone: "(555) 504-2211",
        email: "jisoo.kim@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-4-location-1",
        created_at: "2026-02-24T13:00:00.000Z",
        label: "Clinic",
        street_address: "415 Westlake Blvd",
        city: "Irvine",
        state: "CA",
        postal_code: "92618",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Family prefers Tuesdays and Thursdays.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-4-insurance-1",
        created_at: "2026-02-24T13:00:00.000Z",
        insurance_name: "Cigna",
        insurance_type: "commercial",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "CGN-778345",
        group_number: "GRP-3821",
        plan_name: "Open Access Plus",
        subscriber_relationship: "child",
        status: "active",
        copay_amount: 30,
        coinsurance_percentage: 15,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    authorizations: [
      {
        id: "demo-client-4-auth-1",
        created_at: "2026-03-15T15:00:00.000Z",
        insurance_id: "demo-client-4-insurance-1",
        payor_type: "insurance",
        service_type: "Adaptive Behavior Treatment by Technician",
        billing_code: "97153",
        treatment_requested: "Center-based ABA, 15 hours/week",
        units_requested: 260,
        units_used: 18,
        units_per_week_authorized: 60,
        rate_per_unit: undefined,
        start_date: "2026-03-20",
        end_date: "2026-06-20",
        status: "submitted",
        auth_reference_number: "AUTH-48219",
        requires_prior_auth: true,
        notes: "",
        services: [
          {
            id: "demo-client-4-auth-service-1",
            authorization_id: "",
            service_type: "Adaptive Behavior Treatment (97153)",
            billing_code: "97153",
            custom_billing_code: "",
            use_auth_dates: true,
            start_date: "",
            end_date: "",
            hours_per_week: 15,
            hours_per_auth: 195,
            units_per_week: 60,
            units_per_auth: 780,
            units_used: 18,
            use_calculated_values: true,
            notes: "",
          },
        ],
      },
    ],
    tasks: [
      {
        id: "demo-client-4-task-1",
        created_at: "2026-03-24T08:30:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Follow up with Cigna reviewer",
        content: "",
        status: "pending",
        due_date: "2026-03-26",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-5", {
    referral_source: "word_of_mouth",
    service_start_date: "2026-01-12",
    child_diagnosis: ["Autism Spectrum Disorder"],
    child_primary_concerns: "Active therapy case focused on social communication and daily routines.",
    child_aba_history: "Has been in ABA for 10 weeks with strong attendance.",
    child_school_name: "Oak Ridge Elementary",
    child_school_district: "Round Rock ISD",
    child_grade_level: "2nd",
    child_pediatrician_name: "Dr. Sarah Monroe",
    child_pediatrician_phone: "(555) 605-1124",
    notes: "Parents are open to adding caregiver training on Saturdays.",
    parents: [
      {
        id: "demo-client-5-parent-1",
        created_at: "2026-01-09T10:15:00.000Z",
        first_name: "Jessica",
        last_name: "Williams",
        relationship: "mother",
        phone: "(555) 605-8834",
        email: "j.williams@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-5-location-1",
        created_at: "2026-01-09T10:15:00.000Z",
        label: "Home",
        street_address: "78 Briarwood Ct",
        city: "Round Rock",
        state: "TX",
        postal_code: "78664",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Primary weekday therapy location.",
        is_primary: true,
        sort_order: 0,
      },
      {
        id: "demo-client-5-location-2",
        created_at: "2026-01-18T10:15:00.000Z",
        label: "School",
        street_address: "1401 Oak Ridge Dr",
        city: "Round Rock",
        state: "TX",
        postal_code: "78664",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Consult coordination with school team once per month.",
        is_primary: false,
        sort_order: 1,
      },
    ],
    insurances: [
      {
        id: "demo-client-5-insurance-1",
        created_at: "2026-01-09T10:15:00.000Z",
        insurance_name: "Blue Cross Blue Shield",
        insurance_type: "commercial",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "BCBS-112978",
        group_number: "GRP-5100",
        plan_name: "Preferred PPO",
        subscriber_relationship: "child",
        status: "active",
        copay_amount: 20,
        coinsurance_percentage: 10,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    authorizations: [
      {
        id: "demo-client-5-auth-1",
        created_at: "2026-01-10T09:45:00.000Z",
        insurance_id: "demo-client-5-insurance-1",
        payor_type: "insurance",
        service_type: "Adaptive Behavior Treatment by Technician",
        billing_code: "97153",
        treatment_requested: "Home ABA, 18 hours/week",
        units_requested: 312,
        units_used: 124,
        units_per_week_authorized: 72,
        rate_per_unit: undefined,
        start_date: "2026-01-12",
        end_date: "2026-04-12",
        status: "approved",
        auth_reference_number: "AUTH-31874",
        requires_prior_auth: true,
        notes: "",
        services: [],
      },
    ],
    documents: [
      {
        id: "demo-client-5-document-1",
        created_at: "2026-01-11T12:00:00.000Z",
        document_type: "treatment_plan",
        label: "Initial treatment plan",
        url: "https://preview.findabatherapy.com/demo-client-5/treatment-plan",
        file_path: "",
        file_name: "initial-treatment-plan.pdf",
        file_description: "",
        file_size: 245810,
        file_type: "application/pdf",
        upload_source: "dashboard",
        uploaded_by: undefined,
        notes: "Shared internally for planning.",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "demo-client-5-task-1",
        created_at: "2026-03-24T10:30:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Prepare parent training recap",
        content: "",
        status: "in_progress",
        due_date: "2026-03-31",
        reminder_at: "",
      },
      {
        id: "demo-client-5-task-2",
        created_at: "2026-03-20T09:00:00.000Z",
        completed_at: "2026-03-21T15:00:00.000Z",
        client_id: "",
        title: "Upload behavior reduction baseline",
        content: "",
        status: "completed",
        due_date: "2026-03-21",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-6", {
    referral_source: "regional_center",
    service_start_date: "2026-02-01",
    child_diagnosis: ["Autism Spectrum Disorder"],
    child_primary_concerns: "Current active case with strong parent participation and school consult needs.",
    child_aba_history: "Transferred from another provider due to relocation.",
    child_school_name: "Garcia Academy",
    child_school_district: "Austin ISD",
    child_grade_level: "kindergarten",
    child_pediatrician_name: "Dr. Paula Gomez",
    child_pediatrician_phone: "(555) 706-0088",
    notes: "Family prefers Spanish-language updates when possible.",
    parents: [
      {
        id: "demo-client-6-parent-1",
        created_at: "2026-01-24T11:15:00.000Z",
        first_name: "Carlos",
        last_name: "Garcia",
        relationship: "father",
        phone: "(555) 706-4456",
        email: "c.garcia@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-6-location-1",
        created_at: "2026-01-24T11:15:00.000Z",
        label: "Home",
        street_address: "504 Luna Park Dr",
        city: "Austin",
        state: "TX",
        postal_code: "78744",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Main therapy location.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-6-insurance-1",
        created_at: "2026-01-24T11:15:00.000Z",
        insurance_name: "Medicaid",
        insurance_type: "medicaid",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "MCD-443210",
        group_number: "",
        plan_name: "Texas Medicaid",
        subscriber_relationship: "child",
        status: "active",
        copay_amount: undefined,
        coinsurance_percentage: undefined,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    authorizations: [
      {
        id: "demo-client-6-auth-1",
        created_at: "2026-02-01T08:00:00.000Z",
        insurance_id: "demo-client-6-insurance-1",
        payor_type: "insurance",
        service_type: "Adaptive Behavior Treatment by Technician",
        billing_code: "97153",
        treatment_requested: "Home ABA, 20 hours/week",
        units_requested: 320,
        units_used: 88,
        units_per_week_authorized: 80,
        rate_per_unit: undefined,
        start_date: "2026-02-01",
        end_date: "2026-05-01",
        status: "approved",
        auth_reference_number: "AUTH-55520",
        requires_prior_auth: true,
        notes: "",
        services: [],
      },
    ],
    tasks: [
      {
        id: "demo-client-6-task-1",
        created_at: "2026-03-23T07:45:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Coordinate April school consult",
        content: "",
        status: "pending",
        due_date: "2026-04-02",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-7", {
    referral_source: "existing_client",
    service_start_date: "2025-12-15",
    child_diagnosis: ["Autism Spectrum Disorder", "ADHD"],
    child_primary_concerns: "Ongoing social skills and emotional regulation goals.",
    child_aba_history: "Established client with consistent parent collaboration.",
    child_school_name: "Pine Crest Elementary",
    child_school_district: "Frisco ISD",
    child_grade_level: "3rd",
    child_pediatrician_name: "Dr. Blake Wilson",
    child_pediatrician_phone: "(555) 807-4400",
    notes: "Family asked about social skills group options for summer.",
    parents: [
      {
        id: "demo-client-7-parent-1",
        created_at: "2025-12-10T15:00:00.000Z",
        first_name: "Rachel",
        last_name: "Thompson",
        relationship: "mother",
        phone: "(555) 807-9912",
        email: "rachel.t@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-7-location-1",
        created_at: "2025-12-10T15:00:00.000Z",
        label: "Clinic",
        street_address: "210 Legacy Pkwy",
        city: "Frisco",
        state: "TX",
        postal_code: "75034",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Primary after-school clinic schedule.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-7-insurance-1",
        created_at: "2025-12-10T15:00:00.000Z",
        insurance_name: "TRICARE",
        insurance_type: "tricare",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "TRI-667891",
        group_number: "",
        plan_name: "TRICARE Select",
        subscriber_relationship: "child",
        status: "active",
        copay_amount: 0,
        coinsurance_percentage: 0,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "demo-client-7-task-1",
        created_at: "2026-03-20T13:15:00.000Z",
        completed_at: null,
        client_id: "",
        title: "Review social goals with BCBA",
        content: "",
        status: "pending",
        due_date: "2026-04-01",
        reminder_at: "",
      },
    ],
  }),
  createDemoClientDetail("demo-client-8", {
    referral_source: "google",
    service_start_date: "2025-05-05",
    service_end_date: "2026-03-10",
    discharge_reason: "Goals met and family transitioned to school-based supports.",
    child_diagnosis: ["Autism Spectrum Disorder"],
    child_primary_concerns: "Successfully completed discharge planning after steady progress.",
    child_school_name: "Johnson Intermediate",
    child_school_district: "Leander ISD",
    child_grade_level: "4th",
    child_pediatrician_name: "Dr. Nina Carter",
    child_pediatrician_phone: "(555) 908-7711",
    notes: "Archived example of a completed case with final outcome notes.",
    parents: [
      {
        id: "demo-client-8-parent-1",
        created_at: "2025-09-26T10:20:00.000Z",
        first_name: "David",
        last_name: "Johnson",
        relationship: "father",
        phone: "(555) 908-3345",
        email: "d.johnson@example.com",
        notes: "",
        is_primary: true,
        sort_order: 0,
      },
    ],
    locations: [
      {
        id: "demo-client-8-location-1",
        created_at: "2025-09-26T10:20:00.000Z",
        label: "Home",
        street_address: "3702 Pine Hollow Ln",
        city: "Cedar Park",
        state: "TX",
        postal_code: "78613",
        country: "US",
        latitude: undefined,
        longitude: undefined,
        place_id: "",
        notes: "Final month included parent-led transition planning.",
        is_primary: true,
        sort_order: 0,
      },
    ],
    insurances: [
      {
        id: "demo-client-8-insurance-1",
        created_at: "2025-09-26T10:20:00.000Z",
        insurance_name: "Aetna",
        insurance_type: "commercial",
        is_primary: true,
        effective_date: "2026-01-01",
        expiration_date: "2026-12-31",
        member_id: "AET-998456",
        group_number: "GRP-9921",
        plan_name: "Choice POS II",
        subscriber_relationship: "child",
        status: "inactive",
        copay_amount: 30,
        coinsurance_percentage: 20,
        deductible_total: undefined,
        deductible_remaining: undefined,
        oop_max_total: undefined,
        oop_max_remaining: undefined,
        notes: "",
        sort_order: 0,
      },
    ],
    documents: [
      {
        id: "demo-client-8-document-1",
        created_at: "2026-03-09T17:00:00.000Z",
        document_type: "administrative",
        label: "Discharge summary",
        url: "https://preview.findabatherapy.com/demo-client-8/discharge-summary",
        file_path: "",
        file_name: "discharge-summary.pdf",
        file_description: "",
        file_size: 164992,
        file_type: "application/pdf",
        upload_source: "dashboard",
        uploaded_by: undefined,
        notes: "Example archived summary for preview mode.",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "demo-client-8-task-1",
        created_at: "2026-03-05T14:30:00.000Z",
        completed_at: "2026-03-09T16:00:00.000Z",
        client_id: "",
        title: "Send discharge summary",
        content: "",
        status: "completed",
        due_date: "2026-03-09",
        reminder_at: "",
      },
    ],
  }),
];

export function isDemoClientId(id: string) {
  return id.startsWith("demo-client-");
}

export function getDemoClientDetailById(id: string) {
  return DEMO_CLIENT_DETAILS.find((client) => client.id === id) ?? null;
}
