import type {
  ReferralSourceListItem,
  ReferralTemplate,
} from "@/lib/actions/referrals";

export const DEMO_REFERRAL_NETWORK_SOURCES: ReferralSourceListItem[] = [
  {
    id: "demo-ref-src-1",
    location_id: "demo-location-austin",
    name: "Pediatric Partners of Austin",
    category: "pediatrician",
    stage: "ready_to_contact",
    contactability: "email_verified",
    relationship_health: "neutral",
    phone: "(512) 555-0148",
    website: "https://pediatricpartners.example.com",
    public_email: "referrals@pediatricpartners.example.com",
    contact_form_url: null,
    city: "Austin",
    state: "TX",
    distance_miles: 3.2,
    priority_score: 91,
    fit_score: 94,
    contactability_score: 88,
    confidence_score: 92,
    do_not_contact: false,
    last_contacted_at: "2026-03-18T14:00:00.000Z",
    next_follow_up_at: "2026-03-29T14:00:00.000Z",
    notes_summary: "Strong fit for early diagnosis referrals and insurance-friendly families.",
    google_rating: 4.8,
    google_rating_count: 129,
    updated_at: "2026-03-20T14:00:00.000Z",
  },
  {
    id: "demo-ref-src-2",
    location_id: "demo-location-austin",
    name: "Little Oaks Speech & OT",
    category: "speech_therapy",
    stage: "contacted",
    contactability: "contact_form_only",
    relationship_health: "warm",
    phone: "(512) 555-0181",
    website: "https://littleoaks.example.com",
    public_email: null,
    contact_form_url: "https://littleoaks.example.com/contact",
    city: "Round Rock",
    state: "TX",
    distance_miles: 8.7,
    priority_score: 84,
    fit_score: 86,
    contactability_score: 72,
    confidence_score: 81,
    do_not_contact: false,
    last_contacted_at: "2026-03-12T10:30:00.000Z",
    next_follow_up_at: "2026-03-26T10:30:00.000Z",
    notes_summary: "Cross-referral opportunity for speech + ABA co-treatment families.",
    google_rating: 4.7,
    google_rating_count: 61,
    updated_at: "2026-03-19T14:00:00.000Z",
  },
  {
    id: "demo-ref-src-3",
    location_id: "demo-location-austin",
    name: "Sunrise Developmental Pediatrics",
    category: "developmental_pediatrician",
    stage: "active_referrer",
    contactability: "email_verified",
    relationship_health: "strong",
    phone: "(512) 555-0122",
    website: "https://sunrisedevpeds.example.com",
    public_email: "careteam@sunrisedevpeds.example.com",
    contact_form_url: null,
    city: "Austin",
    state: "TX",
    distance_miles: 5.4,
    priority_score: 97,
    fit_score: 96,
    contactability_score: 93,
    confidence_score: 95,
    do_not_contact: false,
    last_contacted_at: "2026-03-22T09:15:00.000Z",
    next_follow_up_at: "2026-04-08T09:15:00.000Z",
    notes_summary: "Already referring monthly. Good partner for intake packet handoff.",
    google_rating: 4.9,
    google_rating_count: 87,
    updated_at: "2026-03-22T09:15:00.000Z",
  },
  {
    id: "demo-ref-src-4",
    location_id: "demo-location-austin",
    name: "Northview Child Psychology",
    category: "child_psychologist",
    stage: "discovered",
    contactability: "phone_only",
    relationship_health: "neutral",
    phone: "(512) 555-0190",
    website: "https://northviewpsych.example.com",
    public_email: null,
    contact_form_url: null,
    city: "Cedar Park",
    state: "TX",
    distance_miles: 12.1,
    priority_score: 73,
    fit_score: 79,
    contactability_score: 48,
    confidence_score: 70,
    do_not_contact: false,
    last_contacted_at: null,
    next_follow_up_at: null,
    notes_summary: "Potential autism evaluation partner. Needs contact enrichment.",
    google_rating: 4.6,
    google_rating_count: 43,
    updated_at: "2026-03-17T08:00:00.000Z",
  },
  {
    id: "demo-ref-src-5",
    location_id: "demo-location-austin",
    name: "Oakridge Elementary Special Services",
    category: "school",
    stage: "ready_to_contact",
    contactability: "email_unverified",
    relationship_health: "neutral",
    phone: "(512) 555-0104",
    website: "https://oakridgeisd.example.com",
    public_email: "counselor@oakridgeisd.example.com",
    contact_form_url: null,
    city: "Pflugerville",
    state: "TX",
    distance_miles: 9.8,
    priority_score: 78,
    fit_score: 82,
    contactability_score: 66,
    confidence_score: 74,
    do_not_contact: false,
    last_contacted_at: null,
    next_follow_up_at: "2026-03-31T15:00:00.000Z",
    notes_summary: "Good fit for school-aged after-school ABA referrals.",
    google_rating: null,
    google_rating_count: null,
    updated_at: "2026-03-21T16:40:00.000Z",
  },
  {
    id: "demo-ref-src-6",
    location_id: "demo-location-austin",
    name: "Riverstone Neurology Clinic",
    category: "pediatric_neurologist",
    stage: "do_not_contact",
    contactability: "email_verified",
    relationship_health: "cold",
    phone: "(512) 555-0177",
    website: "https://riverstoneneuro.example.com",
    public_email: "frontdesk@riverstoneneuro.example.com",
    contact_form_url: null,
    city: "Austin",
    state: "TX",
    distance_miles: 6.9,
    priority_score: 52,
    fit_score: 61,
    contactability_score: 84,
    confidence_score: 59,
    do_not_contact: true,
    last_contacted_at: "2026-02-18T11:00:00.000Z",
    next_follow_up_at: null,
    notes_summary: "Paused for now after requesting no further outreach.",
    google_rating: 4.4,
    google_rating_count: 34,
    updated_at: "2026-03-01T12:00:00.000Z",
  },
];

export const DEMO_REFERRAL_TEMPLATES: ReferralTemplate[] = [
  {
    id: "demo-ref-template-1",
    name: "Referral Intro",
    template_type: "intro",
    subject: "Referral partnership with {{agency_name}}",
    body: "Hi {{contact_name}},\n\nWe support families across Austin with ABA services and would love to be a referral option for your office.\n\nBest,\n{{agency_name}}",
    is_default: true,
    is_active: true,
    updated_at: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "demo-ref-template-2",
    name: "Follow Up",
    template_type: "follow_up",
    subject: "Following up from {{agency_name}}",
    body: "Hi {{contact_name}},\n\nFollowing up in case your team needs an ABA partner for newly diagnosed families.\n\nThank you,\n{{agency_name}}",
    is_default: false,
    is_active: true,
    updated_at: "2026-03-20T10:00:00.000Z",
  },
];

export const DEMO_REFERRAL_LOCATIONS = [
  {
    id: "demo-location-austin",
    label: "Austin Clinic",
    city: "Austin",
    state: "TX",
  },
];
